Lumiere/Models/Film.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Lumiere.Models
{
    public class Film
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int AgeLimit { get; set; }
        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }
        public double Rating { get; set; }
        public TimeSpan Duration { get; set; }
        public List<FilmFeedback> Feedbacks { get; set; }
        public List<FilmPoster> Posters { get; set; }
        public FilmTrailer Trailer { get; set; }
        public List<FilmSeance> Seances { get; set; }

        public Film()
        {
            Feedbacks = new List<FilmFeedback>();
            Posters = new List<FilmPoster>();
            Trailer = new FilmTrailer();
            Seances = new List<FilmSeance>();
        }
    }
}

Lumiere/ViewModels/CreateSeanceViewModel.cs
using System;

namespace Lumiere.ViewModels
{
    public class CreateSeanceViewModel
    {
        public DateTime Date { get; set; }
        public DateTime Time { get; set; }
        public int Price { get; set; }
        public int RoomNumber { get; set; }
        public Guid FilmId { get; set; }
    }
}

Lumiere/ViewModels/FilmViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Lumiere.ViewModels
{
    public class FilmViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int AgeLimit { get; set; }

        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }
        public TimeSpan Duration { get; set; }
        public string TrailerUrl { get; set; }
    }
}

Lumiere/Controllers/FilmController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Lumiere.Models;
using Lumiere.Repositories;
using Lumiere.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Lumiere.Controllers
{
    public class FilmController : Controller
    {
        private readonly IFilmRepository _filmRepository;
        private readonly ITrailerRepository _trailerRepository;
        private readonly IWebHostEnvironment _appEnvironment;
        private readonly IPosterRepository _posterRepository;

        public FilmController(IFilmRepository filmRepository, ITrailerRepository trailerRepository, IWebHostEnvironment appEnvironment, IPosterRepository posterRepository)
        {
            _filmRepository = filmRepository;
            _trailerRepository = trailerRepository;
            _appEnvironment = appEnvironment;
            _posterRepository = posterRepository;
        }

        [HttpGet]
        public async Task<IActionResult> Index(Guid id)
        {
            Film film = await _filmRepository.GetByIdAsync(id);
            if (film == null)
                return NotFound();

            return View(film);
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create(FilmViewModel model, IFormFileCollection posters)
        {
            if (!ModelState.IsValid)
                return View(model);

            Film film = new Film
            {
                Name = model.Name,
                Description = model.Description,
                AgeLimit = model.AgeLimit,
                ReleaseDate = model.ReleaseDate,
                Duration = model.Duration
            };
            await _filmRepository.CreateAsync(film);

            FilmTrailer trailer = new FilmTrailer
            {
                Url = model.TrailerUrl,
                FilmId = film.Id
            };
            await _trailerRepository.CreateAsync(trailer);
            film.Trailer = trailer;

            List<FilmPoster> filmPosters = await SavePostersImages(film.Id, posters);
            film.Posters.AddRange(filmPosters);

            await _filmRepository.UpdateAsync(film);

            return RedirectToAction("Index", "Admin");
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Update(Guid id)
        {
            Film film = await _filmRepository.GetByIdAsync(id);
            if (film == null)
                return NotFound();

            FilmViewModel filmViewModel = new FilmViewModel
            {
                Id = film.Id,
                Name = film.Name,
                Description = film.Description,
                AgeLimit = film.AgeLimit,
                ReleaseDate = film.ReleaseDate,
                Duration = film.Duration,
                TrailerUrl = film.Trailer.Url
            };

            return View(filmViewModel);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Update(FilmViewModel model, IFormFileCollection posters)
        {
            if (!ModelState.IsValid)
                return View(model);

            Film film = await _filmRepository.GetByIdAsync(model.Id);

            film.Id = model.Id;
            film.Name = model.Name;
            film.Description = model.Description;
            film.AgeLimit = model.AgeLimit;
            film.ReleaseDate = model.ReleaseDate;
            film.Duration = model.Duration;
            film.Trailer.Url = model.TrailerUrl;

            List<FilmPoster> filmPosters = await SavePostersImages(film.Id, posters);
            film.Posters.AddRange(filmPosters);

            await _filmRepository.UpdateAsync(film);

            return RedirectToAction("Index", "Admin");
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(Guid id)
        {
            Film film = await _filmRepository.GetByIdAsync(id);
            if (film == null)
                return NotFound();

            foreach(FilmPoster poster in film.Posters)
            {
                DeletePosterImage(poster.Url);
            }

            await _filmRepository.DeleteAsync(film);

            return RedirectToAction("Index", "Admin");
        }

        private async Task<List<FilmPoster>> SavePostersImages(Guid filmId, IFormFileCollection posters)
        {
            List<FilmPoster> filmPosters = new List<FilmPoster>();
            Guid posterId = Guid.NewGuid();
            foreach (var image in posters)
            {
                using (var fileStream = new FileStream($"{_appEnvironment.WebRootPath}/img/posters/poster_{posterId}.png", FileMode.Create, FileAccess.Write))
                {
                    image.CopyTo(fileStream);

                    FilmPoster filmPoster = new FilmPoster
                    {
                        Url = $"/img/posters/poster_{posterId}.png",
                        FilmId = filmId
                    };
                    await _posterRepository.CreateAsync(filmPoster);

                    filmPosters.Add(filmPoster);
                }
                posterId = Guid.NewGuid();
            }

            return filmPosters;
        }

        private void DeletePosterImage(string posterUrl)
        {
            try
            {
                System.IO.File.Delete(_appEnvironment.WebRootPath + posterUrl);
            }
            catch (DirectoryNotFoundException dirNotFound)
            {
                throw new Exception(dirNotFound.Message);
            }
        }
    }
}

Lumiere/Controllers/SeanceController.cs
using Lumiere.Models;
using Lumiere.Repositories;
using Lumiere.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Lumiere.Controllers
{
    public class SeanceController : Controller
    {
        private readonly IFilmRepository _filmRepository;
        private readonly ISeanceRepository _seanceRepository;

        public SeanceController(IFilmRepository filmRepository, ISeanceRepository seanceRepository)
        {
            _filmRepository = filmRepository;
            _seanceRepository = seanceRepository;
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create(CreateSeanceViewModel model)
        {
            if (!ModelState.IsValid)
                return PartialView(model);

            Film film = await _filmRepository.GetByIdAsync(model.FilmId);
            if(film == null)
            {
                ModelState.AddModelError(string.Empty, "Фильм не найден.");
                return PartialView(model);
            }

            FilmSeance seance = new FilmSeance
            {
                Date = model.Date,
                Time = model.Time,
                Price = model.Price,
                FilmId = model.FilmId,
                RoomNumber = model.RoomNumber
            };

            await _seanceRepository.CreateAsync(seance);

            film.Seances.Add(seance);
            await _filmRepository.UpdateAsync(film);

            return RedirectToAction("Index", "Admin");
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(Guid id)
        {
            FilmSeance seance = await _seanceRepository.GetByIdAsync(id);
            if (seance == null)
                return NotFound();

            await _seanceRepository.DeleteAsync(seance);

            return RedirectToAction("Index", "Admin");
        }
    }
}

Lumiere/Views/Film/Create.cshtml
@model Lumiere.ViewModels.FilmViewModel

@{
    ViewData["Title"] = "Create";
}
<div class="container--register">
    <div class="container w-75 mt-5">
        <!-- title -->
        <h4 class="text-center mb-4">Добавить фильм</h4>
        <hr>
        <!-- form -->
        <div class="d-flex justify-content-center">
            <form class="mb-4" style="min-width: 30vw;" enctype="multipart/form-data" method="post" asp-controller="Film" asp-action="Create">
                <div asp-validation-summary="All"></div>

                <div class="form-group">
                    <label asp-for="Name">Название</label>
                    <input type="text" asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Description">Описание</label>
                    <input type="text" asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description"></span>
                </div>

                <div class="form-row d-flex justify-content-center">
                    <div class="form-group col-md-3">
                        <label asp-for="AgeLimit">Ограничение</label>
                        <input type="number" asp-for="AgeLimit" class="form-control" />
                        <span asp-validation-for="AgeLimit"></span>
                    </div>

                    <div class="form-group col" style="max-width: 165px">
                        <label asp-for="ReleaseDate">Дата релиза</label>
                        <input type="date" asp-for="ReleaseDate" class="form-control" />
                        <span asp-validation-for="ReleaseDate"></span>
                    </div>

                    <div class="form-group col" style="max-width: 115px">
                        <label asp-for="Duration">Длительность</label>
                        <input type="time" asp-for="Duration" class="form-control" />
                        <span asp-validation-for="Duration"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="TrailerUrl">Ссылка на трейлер</label>
                    <input type="url" asp-for="TrailerUrl" class="form-control" />
                    <span asp-validation-for="TrailerUrl"></span>
                </div>

                <div class="form-group">
                    <label for="posters">Постеры</label>
                    <input type="file" accept="image/*" multiple name="posters" class="form-control-file" />
                </div>

                <div class="text-center">
                    <input type="submit" class="btn btn-secondary mt-2" value="Создать" />
                </div>
            </form>
            <br>
        </div>

    <hr />  
    </div>
</div>

Lumiere/Views/Film/CreateSeance.cshtml
@model Lumiere.ViewModels.CreateSeanceViewModel

    <form name="registration" id="form" method="post" asp-controller="Seance" asp-action="Create" class="p-4 w-75">
        <input type="hidden" asp-for="FilmId"/>    
        <div class="form-row d-flex justify-content-around">
            <div class="form-group col-md-5">
                <label for="sessionDate">Дата сеанса</label>
                <input type="date" asp-for="Date" required class="form-control" />
            </div>
            <div class="form-group">
                <label for="sessionTime col-md-3">Время</label>
                <input type="time" asp-for="Time" required class="form-control" />
            </div>
            <div class="form-group col-md-4">
                <label for="sessionTime">Цена билета</label>
                <input type="number" asp-for="Price" required class="form-control" />
            </div>
        </div>
        <div class="col-md-5 m-auto">
            <input type="submit" value="Добавить" required class="form-control btn btn-secondary" />
        </div>
    </form>

Lumiere/Views/Film/FilmCard.cshtml
@model Lumiere.Models.Film

    <div class="card mr-2 mb-3" style="width: 13rem;">
        <a asp-controller="Film" asp-action="Index" asp-route-id=@Model.Id >
            <img src=@Model?.Posters?.First()?.Url class="card-img-top" alt="movie poster">
        </a>
        <div class="card-body text-center">
            <a asp-controller="Film" asp-action="Index" asp-route-id=@Model.Id >
                <h6 class="card-title text-body">@Model.Name</h6>
            </a>

            @foreach(FilmSeance seance in Model.Seances) {
                if (seance.Date == DateTime.Today)
                {
                    <span class="card-text">@seance.Time.ToString("t")</span> 
                }
            }
        </div>
    </div>

Lumiere/Views/Film/Index.cshtml
@model Lumiere.Models.Film

@{
    ViewData["Title"] = "Index";
}

<main id="container--register">
    <div class="container w-75 pl-5 pr-5 pb-4">
        <!-- title container -->
        <div class="d-flex justify-content-between text-center align-items-center mb-4">
            <h4 class="text-center flex-grow-1">@Model.Name @Model.AgeLimit+</h4>

            @if (User.IsInRole("admin"))
            {
                <a class="text-info text-dark" asp-controller="Film" asp-action="Update" asp-route-id=@Model.Id>
                    <i class="icofont-pencil-alt-2 ml-2 mr-4"></i>
                </a>
            }
        </div>
        <hr class="mb-0">

        <div class="row pt-4 mb-4 bg-gradient">
            <!-- left trailer column -->
            <div class="col col-lg-8">
                <iframe width="100%" height="315" src=@Model.Trailer.Url frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
            <!-- right details column -->
            <div class="col pl-1">
                <div class="d-flex flex-column mb-4 text-center justify-content-between">
                    <span class="text-dark mb-3"><b>Рейтинг Кинопоиска: </b><span id="raiting"></span></span>
                    <span class="text-dark mb-3">драма, приключение, семейный</span>
                    <span class="text-dark">Формат: 2D</span>
                    <span class="text-dark mb-4">Длительность: @Model.Duration.ToString("t")</span>
                    <span class="h6">Сеансы сегодня, @DateTime.Today.ToString("m"):</span>
                    <div class="d-flex justify-content-around flex-wrap">
                        @foreach (FilmSeance seance in Model.Seances)
                        {
                            if (seance.Date == DateTime.Today)
                            {
                                <span class="h6 mr-1">@seance.Time.ToString("t")</span>
                            }
                        }
                    </div>
                    <button type="button" class="btn btn-warning align-self-center mt-4">
                        <i class="icofont-film pr-2"></i>
                        Забронировать
                    </button>
                </div>
            </div>
        </div>
        <!-- movie description -->
        <div class="text-center pl-5 pr-5 h5">
            @Model.Description
        </div>
    </div>
    <hr />
</main>

@await Html.PartialAsync("Posters")

Lumiere/Views/Film/Update.cshtml
@model Lumiere.ViewModels.FilmViewModel

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<div>
    <form enctype="multipart/form-data" method="post" asp-controller="Film" asp-action="Update">
        <input type="hidden" asp-for="Id" />

        <div asp-validation-summary="All"></div>

        <div>
            <label asp-for="Name">Name</label>
            <input type="text" asp-for="Name" />
            <span asp-validation-for="Name"></span>
        </div>

        <div>
            <label asp-for="Description">Description</label>
            <input type="text" asp-for="Description" />
            <span asp-validation-for="Description"></span>
        </div>

        <div>
            <label asp-for="AgeLimit">Age limit</label>
            <input type="number" asp-for="AgeLimit" />
            <span asp-validation-for="AgeLimit"></span>
        </div>

        <div>
            <label asp-for="ReleaseDate">Release date</label>
            <input type="date" asp-for="ReleaseDate" />
            <span asp-validation-for="ReleaseDate"></span>
        </div>

        <div>
            <label asp-for="Duration">Duration</label>
            <input type="time" asp-for="Duration" />
            <span asp-validation-for="Duration"></span>
        </div>

        <div>
            <label asp-for="TrailerUrl">Trailer url</label>
            <input type="url" asp-for="TrailerUrl" />
            <span asp-validation-for="TrailerUrl"></span>
        </div>

        <div>
            <input type="file" accept="image/*" multiple name="posters" />
        </div>

        <div>
            <input type="submit" value="Редактировать" />
        </div>
    </form>

    <div>
        @await Html.PartialAsync("CreateSeance", new Lumiere.ViewModels.CreateSeanceViewModel { FilmId = Model.Id })
    </div>
</div>